Fix restructure fs (#13)
* Workfile restructuring and remove automatic mongodb startup from dockerfile to prevent conflict

* Removed db data and added gitignore

* Retrigger

* Adapt mongodb to usage case

* Modified some mongo dict defaults

* Testing FS copyable mongo db

* Added mongodb env var to setup

* Running docker containers with mongodb network flag

* Fixed test paths

* Fix warnings

* setup concurrency groups

* Runnerwise semitemp subdir

* Always cleanup semitemp

* Copy cache to allow for access concurrency

* Retrigger to test concurrency

* Removed group

* Fix EOF error

* Retrigger to test concurrency

* Cache to registry instead of locally if registry available

* registry caching removed local caching

* Fix some syntax

* Fix trigger logic

* Fix more trigger logic

* Move to local registry

* Added additional build cache tag

* Retrigger build

---------

Co-authored-by: amadou cisse <ga84jog@mytum.de>

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -71,7 +71,7 @@ jobs:
           DOCKER_VOLUME_MOUNTS="\
            -v $DOCKER_CACHE_DIR/.github-action-cache/control-dataset:/workdir/tests/data/control-dataset\
            -v $DOCKER_CACHE_DIR/.github-action-cache/mimiciii-demo:/workdir/tests/data/mimiciii-demo\
-           -v $DOCKER_CACHE_DIR/.github-action-cache/semitemp:/workdir/tests/data/semitemp\
+           -v $DOCKER_CACHE_DIR/.github-action-cache/${{ runner.name }}/semitemp:/workdir/tests/data/semitemp\
            -v $DOCKER_CACHE_DIR/.github-action-cache/bash-results:/workdir/tests/data/bash-results\
            -v $DOCKER_CACHE_DIR/.github-action-cache/pytest-results:/workdir/tests/data/pytest-results"
          
@@ -93,6 +93,32 @@ jobs:
           echo "bash_results=$BASH_RESULTS" >> $GITHUB_OUTPUT
           echo "pytest_results=$PYTEST_RESULTS" >> $GITHUB_OUTPUT
 
+      - name: Check if local registry is running
+        id: check_registry
+        run: |
+          echo "Checking if local registry is running at localhost:5000..."
+          check_registry() {
+              local url=$1
+              if curl -s -f -m 5 "http://${url}/v2/_catalog" > /dev/null 2>&1; then
+                  return 0
+              else
+                  return 1
+              fi
+          }
+
+          if check_registry "localhost:5000"; then
+              echo "local_registry=true" >> $GITHUB_OUTPUT
+              echo "Local registry is running on localhost:5000."
+              echo "registry_host=localhost:5000" >> $GITHUB_OUTPUT
+          elif check_registry "registry:5000"; then
+              echo "local_registry=true" >> $GITHUB_OUTPUT
+              echo "registry_host=registry:5000" >> $GITHUB_OUTPUT
+              echo "Local registry is running on registry:5000 (Docker network)."
+          else
+              echo "local_registry=false" >> $GITHUB_OUTPUT
+              echo "Error: No local registry is running or accessible." >&2
+          fi
+
       # => 4. Create cache directory if runing locally
       - name: Set up Docker cache/output directory on self-hosted
         if: runner.environment == 'self-hosted'
@@ -109,7 +135,14 @@ jobs:
           echo "DOCKER_CACHE_DIR=$DOCKER_CACHE_DIR" >> $GITHUB_ENV
           
           mkdir -p $DOCKER_CACHE_DIR
+          mkdir -p $DOCKER_CACHE_DIR/.buildx-cache
           mkdir -p $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/
+
+          if [[ steps.check_registry.outputs.local_registry == 'false' ]]; then
+            echo "Copying docker cache from $DOCKER_CACHE_DIR/.buildx-cache to $DOCKER_CACHE_DIR/${{ runner.name }}/.buildx-cache"
+            mkdir -p "$DOCKER_CACHE_DIR/${{ runner.name }}/.buildx-cache"
+            cp -r "$DOCKER_CACHE_DIR/.buildx-cache" "$DOCKER_CACHE_DIR/${{ runner.name }}/"
+          fi
 
           echo "::group::DOCKER_CACHE_DIR"
           echo $DOCKER_CACHE_DIR
@@ -138,10 +171,12 @@ jobs:
       
       # => 6. Setup cache on runner machine: self-hosted
       - name: Cache Docker layers on self-hosted
-        if: runner.environment == 'self-hosted'
+        if: |
+          runner.environment == 'self-hosted' &&
+          steps.check_registry.outputs.local_registry == 'false'
         uses: maxnowack/local-cache@v2
         with: 
-          path: ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
+          path: ${{ env.DOCKER_CACHE_DIR }}/${{ runner.name }}/.buildx-cache
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-   
@@ -156,32 +191,6 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-buildx-
 
-      - name: Check if local registry is running
-        id: check_registry
-        run: |
-          echo "Checking if local registry is running at localhost:5000..."
-          check_registry() {
-              local url=$1
-              if curl -s -f -m 5 "http://${url}/v2/_catalog" > /dev/null 2>&1; then
-                  return 0
-              else
-                  return 1
-              fi
-          }
-
-          if check_registry "localhost:5000"; then
-              echo "local_registry=true" >> $GITHUB_OUTPUT
-              echo "Local registry is running on localhost:5000."
-              echo "registry_host=localhost:5000" >> $GITHUB_OUTPUT
-          elif check_registry "registry:5000"; then
-              echo "local_registry=true" >> $GITHUB_OUTPUT
-              echo "registry_host=registry:5000" >> $GITHUB_OUTPUT
-              echo "Local registry is running on registry:5000 (Docker network)."
-          else
-              echo "local_registry=false" >> $GITHUB_OUTPUT
-              echo "Error: No local registry is running or accessible." >&2
-          fi
-
       # => 7. Build and push Docker image: self-hosted (part 1) 
       #       - local registry reachable:
       #           - build and push to local registry
@@ -192,21 +201,38 @@ jobs:
       #           - build and export image locally
       #           - don't push to local registry
       #           - push to docker hub in subsequent step
-      - name: Build and export Docker image
+      - name: Build and push to local registry
+        if: |
+          steps.check_registry.outputs.local_registry == 'true' && 
+          runner.environment == 'self-hosted'
         uses: docker/build-push-action@v6
         with:
           context: .
-          file: .devcontainer/Dockerfile.ci
-          load: ${{ steps.check_registry.outputs.local_registry != 'true' }}
-          push: ${{ steps.check_registry.outputs.local_registry == 'true' }}
+          file: ./docker/Dockerfile.ci
+          push: true
           tags: |
             tensorpod/pymimic3:latest
             tensorpod/pymimic3:${{ env.BRANCH_NAME }}
-            ${{ steps.check_registry.outputs.local_registry == 'true' && 'localhost:5000/pymimic3:latest' || '' }}
-            ${{ steps.check_registry.outputs.local_registry == 'true' && format('localhost:5000/pymimic3:{0}', env.BRANCH_NAME) || '' }}
+            localhost:5000/pymimic3:latest
+            localhost:5000/pymimic3:${{ env.BRANCH_NAME }}
+          cache-from: type=registry,ref=localhost:5000/pymimic3:buildcache
+          cache-to: type=registry,ref=localhost:5000/pymimic3:buildcache,mode=max
+
+      - name: Build and export to tar
+        if: |
+          steps.check_registry.outputs.local_registry != 'true' && 
+          runner.environment == 'self-hosted'
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./docker/Dockerfile.ci
+          load: true
+          tags: |
+            tensorpod/pymimic3:latest
+            tensorpod/pymimic3:${{ env.BRANCH_NAME }}
           cache-from: type=local,src=${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
           cache-to: type=local,dest=${{ env.DOCKER_CACHE_DIR }}/.buildx-cache-new,mode=max
-          outputs: ${{ steps.check_registry.outputs.local_registry != 'true' && format('type=docker,dest={0}', env.DOCKER_IMAGE_TAR) || '' }}
+          outputs: type=docker,dest=${{ env.DOCKER_IMAGE_TAR }}
 
       # => 7. Build and push Docker image: github hosted
       - name: Build and export Docker image on github-hosted
@@ -214,7 +240,7 @@ jobs:
         uses: docker/build-push-action@v6
         with:
           context: .
-          file: .devcontainer/Dockerfile.ci
+          file: ./docker/Dockerfile.ci
           push: ${{ github.event_name != 'pull_request' }}
           tags: |
             tensorpod/pymimic3:latest
@@ -249,10 +275,11 @@ jobs:
 
       # => 9. Move the cache with -new suffix to original cache
       - name: Move cache
+        if: ${{ steps.check_registry.outputs.local_registry == 'false' }}
         run: |
           if [ "${{ runner.environment }}" = "self-hosted" ]; then
-            rm -rf $DOCKER_CACHE_DIR/.buildx-cache
-            mv $DOCKER_CACHE_DIR/.buildx-cache-new $DOCKER_CACHE_DIR/.buildx-cache
+            rm -rf $DOCKER_CACHE_DIR/${{ runner.name }}/.buildx-cache
+            mv $DOCKER_CACHE_DIR/${{ runner.name }}/.buildx-cache-new $DOCKER_CACHE_DIR/.buildx-cache
           elif [ "${{ runner.environment }}" = "github-hosted" ]; then
             rm -rf tmp/.buildx-cache
             mv tmp/.buildx-cache-new tmp/.buildx-cache
@@ -290,6 +317,8 @@ jobs:
 # Pytest run test
 
   setup-control-dataset:
+    concurrency:
+      group: setup-control-dataset
     runs-on: self-hosted
     needs: build-and-push
     env: 
@@ -373,6 +402,8 @@ jobs:
       - name: Run fixture setup tests
         shell: bash
         run: |
+          # Create the semitemp directory
+          mkdir -p $DOCKER_CACHE_DIR/.github-action-cache/${{ runner.name }}/semitemp
           # Enable color output
           export TERM=xterm-color
           export TERM=xterm-256color
@@ -534,7 +565,7 @@ jobs:
           "$DOCKER_VOLUME_MOUNTS" \
           "$BRANCH_NAME" \
           "$CONTAINER_PYTEST_RESULTS" \
-          "tests/test_datasets/test_readers/test_data_split.py" \
+          "tests/test_datasets/test_data_split.py" \
           "$BASH_RESULTS" \
           "$PYTEST_RESULTS" \
           "test-data-split"
@@ -624,7 +655,7 @@ jobs:
           "$DOCKER_VOLUME_MOUNTS" \
           "$BRANCH_NAME" \
           "$CONTAINER_PYTEST_RESULTS" \
-          "tests/test_datasets/test_preprocessors.py" \
+          "tests/test_datasets/test_preprocessor.py" \
           "$BASH_RESULTS" \
           "$PYTEST_RESULTS" \
           "test-preprocessors"
@@ -899,12 +930,17 @@ jobs:
           "$BASH_RESULTS" \
           "$PYTEST_RESULTS" \
           "test-models"
-
+  Cleanup:
+    if: always()
+    runs-on: self-hosted
+    needs: [test-models]
+    steps:
       - name: Cleanup semitemp directory
         if: always()
         shell: bash
         run: |
-          rm -rf $DOCKER_CACHE_DIR/.github-action-cache/semitemp 2>&1 \
+          rm -rf $DOCKER_CACHE_DIR/.github-action-cache/${{ runner.name }}/semitemp && \
+          rm -rf $DOCKER_CACHE_DIR/${{ runner.name }}/.buildx-cache 2>&1 \
           | tee $BASH_RESULTS/cleanup-semitemp.txt
 
           echo "Exit status: $?"
