Introduced env vars into workflow and improve junitxml outputs

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -18,6 +18,9 @@ env:
     -v $DOCKER_CACHE_DIR/.github-action-cache/semitemp:/workdir/tests/data/semitemp
     -v $DOCKER_CACHE_DIR/.github-action-cache/bash-results:/workdir/tests/data/bash-results
     -v $DOCKER_CACHE_DIR/.github-action-cache/pytest-results:/workdir/tests/data/pytest-results
+  CONTAINER_PYTEST_RESULTS: /workdir/tests/data/pytest-results/${GITHUB_SHA}
+  CONTAINER_BASH_RESULTS: /workdir/tests/data/bash-results/${GITHUB_SHA}
+  GITHUB_ACTION_CACHE:
 
 jobs:
   build-and-push:
@@ -56,7 +59,7 @@ jobs:
       - name: Set up Docker cache/output directory on self-hosted
         if: runner.environment == 'self-hosted'
         run: |
-          echo cache dir is: ${{ env.DOCKER_CACHE_DIR }}
+          echo cache dir is: $DOCKER_CACHE_DIR
           if [ -n "$DOCKER_CACHE_DIR" ]; then
             echo "Using runner's DOCKER_CACHE_DIR: $DOCKER_CACHE_DIR"
           else
@@ -64,16 +67,20 @@ jobs:
             echo "DOCKER_CACHE_DIR not set on runner. Using default: $DOCKER_CACHE_DIR"
           fi
           echo "DOCKER_CACHE_DIR=$DOCKER_CACHE_DIR" >> $GITHUB_ENV
+          
           mkdir -p $DOCKER_CACHE_DIR
           mkdir -p $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/
-          echo "Volume mounts for docker are: $DOCKER_VOLUME_MOUNTS"
-          echo "Volume mounts for docker are: ${{ env.DOCKER_VOLUME_MOUNTS }}"
+
+          mkdir -p $CONTAINER_PYTEST_RESULTS
+          mkdir -p $CONTAINER_BASH_RESULTS
 
 
       # => 5. Extract branch name (may fail on pull requests, untested)
       - name: Extract branch name
         shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
+        run: |
+          echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
+          "DOCKER_IMAGE_TAR=$DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/$BRANCH_NAME.tar" >> $GITHUB_ENV
         id: extract_branch
       
       # => 6. Setup cache on runner machine: self-hosted
@@ -81,7 +88,7 @@ jobs:
         if: runner.environment == 'self-hosted'
         uses: maxnowack/local-cache@v2
         with: 
-          path: ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
+          path: $DOCKER_CACHE_DIR/.buildx-cache
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-   
@@ -105,10 +112,10 @@ jobs:
           push: false
           tags: |
             tensorpod/pymimic3:latest
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}
-          cache-from: type=local,src=${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
-          cache-to: type=local,dest=${{ env.DOCKER_CACHE_DIR }}/.buildx-cache-new,mode=max
-          outputs: type=docker,dest=${{ env.DOCKER_CACHE_DIR }}/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
+            tensorpod/pymimic3:$BRANCH_NAME
+          cache-from: type=local,src=$DOCKER_CACHE_DIR/.buildx-cache
+          cache-to: type=local,dest=$DOCKER_CACHE_DIR/.buildx-cache-new,mode=max
+          outputs: type=docker,dest=$DOCKER_IMAGE_TAR
 
       # => 7. Build and push Docker image: github hosted
       - name: Build and export Docker image on github-hosted
@@ -120,33 +127,33 @@ jobs:
           push: ${{ github.event_name != 'pull_request' }}
           tags: |
             tensorpod/pymimic3:latest
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}
+            tensorpod/pymimic3:$BRANCH_NAME
           cache-from: type=gha
           cache-to: type=gha,mode=max
-          outputs: type=docker,dest=/tmp/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
+          outputs: type=docker,dest=/tmp/.buildx-image-cache/tensorpod/pymimic3/$BRANCH_NAME.tar
 
       - name: Upload artifact
         if: runner.environment == 'github-hosted'
         uses: actions/upload-artifact@v4
         with:
-          name: pymimic3.${{ steps.extract_branch.outputs.branch }}
-          path: /tmp/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
+          name: pymimic3.$BRANCH_NAME
+          path: /tmp/.buildx-image-cache/tensorpod/pymimic3/$BRANCH_NAME.tar
 
       # => 8. Push Docker image
       # It seems the docker image is not automatically loaded after build
       - name: Push Docker image
         if: github.event_name != 'pull_request' && runner.environment == 'self-hosted'
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
+          docker load -i $DOCKER_IMAGE_TAR
           docker push tensorpod/pymimic3:latest
-          docker push tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}
+          docker push tensorpod/pymimic3:$BRANCH_NAME
 
       # => 9. Move the cache with -new suffix to original cache
       - name: Move cache
         run: |
           if [ "${{ runner.environment }}" = "self-hosted" ]; then
-            rm -rf ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
-            mv ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache-new ${{ env.DOCKER_CACHE_DIR }}/.buildx-cache
+            rm -rf $DOCKER_CACHE_DIR/.buildx-cache
+            mv $DOCKER_CACHE_DIR/.buildx-cache-new $DOCKER_CACHE_DIR/.buildx-cache
           elif [ "${{ runner.environment }}" = "github-hosted" ]; then
             rm -rf tmp/.buildx-cache
             mv tmp/.buildx-cache-new tmp/.buildx-cache
@@ -156,7 +163,7 @@ jobs:
       # - name: Scan image for vulnerabilities
       #   uses: anchore/scan-action@v3
       #   with:
-      #     image: "tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }}"
+      #     image: "tensorpod/pymimic3:$BRANCH_NAME"
       #     fail-build: false
       #     severity-cutoff: high
  # # Documentation build and deploy
@@ -194,23 +201,17 @@ jobs:
         run: |
           mkdir -p $DOCKER_CACHE_DIR/.github-action-cache/{pytest-results,bash-results}
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Setup control dataset
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-          bash -ic "cd etc && make testing=true 2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt "
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+          bash -ic "cd etc && make testing=true 2>&1 | tee $CONTAINER_BASH_RESULTS\setup-control-dataset.txt "
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
@@ -224,30 +225,29 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Run fixture setup tests
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-            bash -ic "pytest --no-cleanup -v tests/test_zsetup_all_fixtures.py \
-            2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt"
-          echo "Exit status: $?"
-          if [ $? -ne 0 ]; then
-            echo "The command failed."
-            exit 1
-          fi
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            bash -ic "pytest --no-cleanup --junitxml=$CONTAINER_PYTEST_RESULTS/setup-fixture.xml \
+             -v tests/test_zsetup_all_fixtures.py 2>&1 \
+             | tee $BASH_RESULTS/setup-fixture.txt"
 
+             docker run $DOCKER_VOLUME_MOUNTS \
+             tensorpod/pymimic3:$BRANCH_NAME \
+             bash -ic "python -m tests.pytest_utils.reporting $CONTAINER_PYTEST_RESULTS/setup-fixture.xml"
+             
+             echo "Exit status: $?"
+             if [ $? -ne 0 ]; then
+               echo "The command failed."
+               exit 1
+             fi
 
   test-pytest-utils:
     needs: setup-fixtures
@@ -256,29 +256,31 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Run pytest suite tests
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-          bash -ic "pytest --no-cleanup -v tests/test_pytest_utils.py \
-          2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt"
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            bash -ic "pytest --no-cleanup --junitxml=$CONTAINER_PYTEST_RESULTS/test-pytest-utils.xml \ 
+            -v tests/test_pytest_utils.py 2>&1 | tee $BASH_RESULTS/test-pytest-utils.txt"
+
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
             exit 1
           fi
+
+      - name: Check results
+        run: |
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            bash -ic "python -m tests.pytest_utils.reporting $CONTAINER_PYTEST_RESULTS/test-pytest-utils.xml"
 
 
   test-datasets:
@@ -288,24 +290,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Run dataset tests
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-          bash -ic "pytest --no-cleanup -v tests/test_datasets \
-          2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt"
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            bash -ic "pytest --no-cleanup -v tests/test_datasets 2>&1 \ 
+            | tee $BASH_RESULTS\test-dataset.txt"
+
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
@@ -320,24 +317,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Run preprocessing tests
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-          bash -ic "pytest --no-cleanup -v tests/test_preprocessing \
-          2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt"
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            bash -ic "pytest --no-cleanup -v tests/test_preprocessing \
+            2>&1 | tee $BASH_RESULTS/test-preprocessing.txt"
+
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
@@ -352,24 +344,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Run metrics tests
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-          bash -ic "pytest --no-cleanup -v tests/test_metrics \
-          2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt"
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            bash -ic "pytest --no-cleanup -v tests/test_metrics 2>&1 \
+            | tee $BASH_RESULTS.txt"
+
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
@@ -384,36 +371,32 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # => xx. Extract branch name (may fail on pull requests, untested)
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: extract_branch
-
       - name: Load cached image
         run: |
-          docker load -i $DOCKER_CACHE_DIR/.buildx-image-cache/tensorpod/pymimic3/${{ steps.extract_branch.outputs.branch }}.tar
-          echo "Loaded cached image for testing: ${{ steps.extract_branch.outputs.branch }}"
+          docker load -i $DOCKER_IMAGE_TAR
+          echo "Loaded cached image for testing: $BRANCH_NAME"
           echo docker iamge ls -a
 
       - name: Run model tests
         run: |
-          docker run ${{ env.DOCKER_VOLUME_MOUNTS }} \
-            tensorpod/pymimic3:${{ steps.extract_branch.outputs.branch }} \
-            pytest --no-cleanup -v tests/test_models \
-          2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt
+          docker run $DOCKER_VOLUME_MOUNTS \
+            tensorpod/pymimic3:$BRANCH_NAME \
+            pytest --no-cleanup -v tests/test_models 2>&1 \
+            | tee $BASH_RESULTS.txt
+            $BASH_RESULTS$BASH_RESULTS
+
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
             exit 1
           fi
 
-
       - name: Cleanup semitemp directory
         if: always()
         run: |
-          rm -rf $DOCKER_CACHE_DIR/.github-action-cache/semitemp \
-          2>&1 | tee /workdir/tests/data/bash-results/${GITHUB_SHA}.txt
+          rm -rf $DOCKER_CACHE_DIR/.github-action-cache/semitemp 2>&1 \
+          | tee $BASH_RESULTS.txt
+
           echo "Exit status: $?"
           if [ $? -ne 0 ]; then
             echo "The command failed."
